const corpus = {
    titulus_principalis: "De Bello Gallico, I, 19",
    auctor: "C. Iulius Caesar",
    titulus_secundarius: {
        es: "El dilema de César y su diálogo con Diviciaco",
        en: "Caesar's Dilemma and His Dialogue with Diviciacus",
        zh: "凱撒的兩難與他和迪維西亞庫斯的對話"
    },
    introductio: {
        es: {
            titulus: "Introducción al Capítulo 19",
            contentus: `<p>En este capítulo, César se enfrenta a una decisión compleja. Con pruebas irrefutables de la traición de Dúmnorix, considera que tiene motivos suficientes para castigarlo. Sin embargo, un factor crucial le frena: su profundo respeto y aprecio por Diviciaco, el hermano de Dúmnorix, cuya lealtad a Roma es inquebrantable. Temiendo ofender a este valioso aliado con la ejecución de su hermano, César opta por la diplomacia. Convoca a Diviciaco a una reunión privada, utilizando un intérprete de confianza, para exponerle con tacto las fechorías de Dúmnorix y solicitar su consejo sobre cómo proceder sin dañar su relación.</p>`
        },
        en: {
            titulus: "Introduction to Chapter 19",
            contentus: `<p>In this chapter, Caesar faces a complex decision. With irrefutable proof of Dumnorix's treason, he believes he has sufficient grounds to punish him. However, a crucial factor holds him back: his deep respect and appreciation for Diviciacus, Dumnorix's brother, whose loyalty to Rome is unwavering. Fearing to offend this valuable ally by executing his brother, Caesar opts for diplomacy. He summons Diviciacus to a private meeting, using a trusted interpreter, to tactfully lay out Dumnorix's misdeeds and ask for his advice on how to proceed without damaging their relationship.</p>`
        },
        zh: {
            titulus: "第 19 章介紹",
            contentus: `<p>在這一章中，凱撒面臨一個複雜的決定。有了杜姆諾里格斯叛國的確鑿證據，他認為自己有充分的理由懲罰他。然而，一個關鍵因素使他卻步：他對杜姆諾里格斯的兄弟迪維西亞庫斯深表敬重和讚賞，後者對羅馬的忠誠是堅定不移的。由於擔心處決其兄弟會冒犯這位寶貴的盟友，凱撒選擇了外交途徑。他召集迪維西亞庫斯舉行私人會議，通過一位值得信賴的翻譯，委婉地陳述了杜姆諾里格斯的罪行，並徵求他的意見，如何在不損害他們之間關係的情況下處理此事。</p>`
        }
    },
    textus: {
        id: 19,
        capitula: [
            {
                id_capituli: 19,
                orationes: [
                    {
                        id_orationis: 'o1',
                        original_lat: "Quibus rebus cognitis, cum ad has suspiciones certissimae res accederent, quod per fines Sequanorum Heluetios traduxisset, quod obsides inter eos dandos curasset, quod ea omnia non modo iniussu suo et ciuitatis, sed etiam inscientibus ipsis fecisset, quod a magistratu Haeduorum accusaretur, satis esse causae arbitrabatur quare in eum aut ipse animaduerteret aut ciuitatem animaduertere iuberet.",
                        verba: [
                            { textus: "Quibus", lemma: "qui", morphologia: "Pronombre relativo, ablativo, plural, femenino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "estas", en: "these", zh: "這些" } },
                            { textus: "rebus", lemma: "res", morphologia: "Sustantivo, ablativo, plural, femenino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "cosas", en: "matters", zh: "事情" } },
                            { textus: "cognitis", lemma: "cognosco", morphologia: "Verbo, participio, perfecto, pasivo, ablativo, plural, femenino", syntaxis: "Verbo (de ablativo absoluto)", translatio: { es: "una vez conocidas", en: "having been known", zh: "被知曉後" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "cum", lemma: "cum", morphologia: "Conjunción", syntaxis: "Nexo (Cum histórico)", translatio: { es: "como", en: "since", zh: "由於" } },
                            { textus: "ad", lemma: "ad", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "a", en: "to", zh: "對於" } },
                            { textus: "has", lemma: "hic", morphologia: "Adjetivo demostrativo, acusativo, plural, femenino", syntaxis: "Modificador (de suspiciones)", translatio: { es: "estas", en: "these", zh: "這些" } },
                            { textus: "suspiciones", lemma: "suspicio", morphologia: "Sustantivo, acusativo, plural, femenino", syntaxis: "C. preposicional", translatio: { es: "sospechas", en: "suspicions", zh: "懷疑" } },
                            { textus: "certissimae", lemma: "certus", morphologia: "Adjetivo, nominativo, plural, femenino, superlativo", syntaxis: "Modificador (de res)", translatio: { es: "muy ciertas", en: "most certain", zh: "非常確鑿的" } },
                            { textus: "res", lemma: "res", morphologia: "Sustantivo, nominativo, plural, femenino", syntaxis: "Sujeto", translatio: { es: "pruebas", en: "facts", zh: "事實" } },
                            { textus: "accederent", lemma: "accedo", morphologia: "Verbo, 3ª p, plural, imperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "se añadieran", en: "were added", zh: "被加上" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "quod", lemma: "quod", morphologia: "Conjunción", syntaxis: "Nexo (causal)", translatio: { es: "el hecho de que", en: "the fact that", zh: "即" } },
                            { textus: "per", lemma: "per", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "a través de", en: "through", zh: "通過" } },
                            { textus: "fines", lemma: "finis", morphologia: "Sustantivo, acusativo, plural, masculino", syntaxis: "C. preposicional", translatio: { es: "el territorio", en: "the territory", zh: "領土" } },
                            { textus: "Sequanorum", lemma: "Sequani", morphologia: "Sustantivo, genitivo, plural, masculino", syntaxis: "C. del Nombre", translatio: { es: "de los sécuanos", en: "of the Sequani", zh: "塞夸尼人的" } },
                            { textus: "Heluetios", lemma: "Heluetii", morphologia: "Sustantivo, acusativo, plural, masculino", syntaxis: "Objeto Directo", translatio: { es: "a los helvecios", en: "the Helvetii", zh: "赫爾維蒂人" } },
                            { textus: "traduxisset", lemma: "traduco", morphologia: "Verbo, 3ª p, singular, pluscuamperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "había hecho pasar", en: "he had led", zh: "他曾帶領...通過" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "quod", lemma: "quod", morphologia: "Conjunción", syntaxis: "Nexo (causal)", translatio: { es: "que", en: "that", zh: "即" } },
                            { textus: "obsides", lemma: "obses", morphologia: "Sustantivo, acusativo, plural, masculino", syntaxis: "Objeto Directo", translatio: { es: "rehenes", en: "hostages", zh: "人質" } },
                            { textus: "inter", lemma: "inter", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "entre", en: "between", zh: "在...之間" } },
                            { textus: "eos", lemma: "is", morphologia: "Pronombre, acusativo, plural, masculino", syntaxis: "C. preposicional", translatio: { es: "ellos", en: "them", zh: "他們" } },
                            { textus: "dandos", lemma: "do", morphologia: "Verbo, gerundivo, acusativo, plural, masculino", syntaxis: "Parte del verbo", translatio: { es: "a ser entregados", en: "to be given", zh: "交換" } },
                            { textus: "curasset", lemma: "curo", morphologia: "Verbo, 3ª p, singular, pluscuamperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "se había encargado", en: "he had arranged", zh: "他曾安排" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "quod", lemma: "quod", morphologia: "Conjunción", syntaxis: "Nexo (causal)", translatio: { es: "que", en: "that", zh: "即" } },
                            { textus: "ea", lemma: "is", morphologia: "Pronombre, acusativo, plural, neutro", syntaxis: "Modificador (de omnia)", translatio: { es: "todas", en: "all", zh: "所有" } },
                            { textus: "omnia", lemma: "omnis", morphologia: "Adjetivo, acusativo, plural, neutro", syntaxis: "Objeto Directo", translatio: { es: "estas cosas", en: "these things", zh: "這些事" } },
                            { textus: "non", lemma: "non", morphologia: "Adverbio", syntaxis: "Negación", translatio: { es: "no", en: "not", zh: "不僅" } },
                            { textus: "modo", lemma: "modo", morphologia: "Adverbio", syntaxis: "Correlativo", translatio: { es: "solo", en: "only", zh: "是" } },
                            { textus: "iniussu", lemma: "iniussus", morphologia: "Sustantivo, ablativo, singular, masculino", syntaxis: "C.C. de Modo", translatio: { es: "sin el permiso", en: "without the order", zh: "未經...的命令" } },
                            { textus: "suo", lemma: "suus", morphologia: "Adjetivo posesivo, ablativo, singular, masculino", syntaxis: "Modificador", translatio: { es: "suyo", en: "his", zh: "他" } },
                            { textus: "et", lemma: "et", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "y", en: "and", zh: "和" } },
                            { textus: "ciuitatis", lemma: "ciuitas", morphologia: "Sustantivo, genitivo, singular, femenino", syntaxis: "C. del Nombre", translatio: { es: "del estado", en: "of the state", zh: "邦國的" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "sed", lemma: "sed", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "sino", en: "but", zh: "而且" } },
                            { textus: "etiam", lemma: "etiam", morphologia: "Adverbio", syntaxis: "Correlativo", translatio: { es: "también", en: "also", zh: "也" } },
                            { textus: "inscientibus", lemma: "insciens", morphologia: "Adjetivo, ablativo, plural, masculino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "sin saberlo", en: "being unaware", zh: "在不知情的情況下" } },
                            { textus: "ipsis", lemma: "ipse", morphologia: "Pronombre, ablativo, plural, masculino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "ellos mismos", en: "they themselves", zh: "他們自己" } },
                            { textus: "fecisset", lemma: "facio", morphologia: "Verbo, 3ª p, singular, pluscuamperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "había hecho", en: "he had done", zh: "他做了" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "quod", lemma: "quod", morphologia: "Conjunción", syntaxis: "Nexo (causal)", translatio: { es: "que", en: "that", zh: "即" } },
                            { textus: "a", lemma: "a", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "por", en: "by", zh: "被" } },
                            { textus: "magistratu", lemma: "magistratus", morphologia: "Sustantivo, ablativo, singular, masculino", syntaxis: "C. Agente", translatio: { es: "el magistrado", en: "the magistrate", zh: "政務官" } },
                            { textus: "Haeduorum", lemma: "Haeduus", morphologia: "Sustantivo, genitivo, plural, masculino", syntaxis: "C. del Nombre", translatio: { es: "de los heduos", en: "of the Aedui", zh: "埃杜伊人的" } },
                            { textus: "accusaretur", lemma: "accuso", morphologia: "Verbo, 3ª p, singular, imperfecto, subjuntivo, pasivo", syntaxis: "Verbo (de subordinada)", translatio: { es: "era acusado", en: "he was being accused", zh: "他被指控" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "satis", lemma: "satis", morphologia: "Adverbio", syntaxis: "Atributo", translatio: { es: "suficiente", en: "enough", zh: "足夠的" } },
                            { textus: "esse", lemma: "sum", morphologia: "Verbo, infinitivo, presente", syntaxis: "Verbo (de infinitiva)", translatio: { es: "haber", en: "there was", zh: "有" } },
                            { textus: "causae", lemma: "causa", morphologia: "Sustantivo, genitivo, singular, femenino", syntaxis: "Genitivo partitivo", translatio: { es: "de motivo", en: "of reason", zh: "理由" } },
                            { textus: "arbitrabatur", lemma: "arbitror", morphologia: "Verbo, 3ª p, singular, imperfecto, indicativo, deponente", syntaxis: "Verbo Principal", translatio: { es: "consideraba", en: "he thought", zh: "他認為" } },
                            { textus: "quare", lemma: "quare", morphologia: "Adverbio interrogativo", syntaxis: "Nexo", translatio: { es: "para", en: "why", zh: "為何" } },
                            { textus: "in", lemma: "in", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "contra", en: "against", zh: "對" } },
                            { textus: "eum", lemma: "is", morphologia: "Pronombre, acusativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "él", en: "him", zh: "他" } },
                            { textus: "aut", lemma: "aut", morphologia: "Conjunción disyuntiva", syntaxis: "Nexo", translatio: { es: "o", en: "either", zh: "或者" } },
                            { textus: "ipse", lemma: "ipse", morphologia: "Pronombre, nominativo, singular, masculino", syntaxis: "Sujeto", translatio: { es: "él mismo", en: "he himself", zh: "他自己" } },
                            { textus: "animaduerteret", lemma: "animaduerto", morphologia: "Verbo, 3ª p, singular, imperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "tomara medidas", en: "should take measures", zh: "採取措施" } },
                            { textus: "aut", lemma: "aut", morphologia: "Conjunción disyuntiva", syntaxis: "Nexo", translatio: { es: "o", en: "or", zh: "或者" } },
                            { textus: "ciuitatem", lemma: "ciuitas", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Sujeto (de infinitiva)", translatio: { es: "al estado", en: "the state", zh: "讓邦國" } },
                            { textus: "animaduertere", lemma: "animaduerto", morphologia: "Verbo, infinitivo, presente, activo", syntaxis: "Verbo (de infinitiva)", translatio: { es: "tomar medidas", en: "to take measures", zh: "採取措施" } },
                            { textus: "iuberet", lemma: "iubeo", morphologia: "Verbo, 3ª p, singular, imperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "ordenara", en: "should order", zh: "命令" } },
                            { textus: ".", lemma: ".", morphologia: "Puntuación", syntaxis: "Fin de oración", translatio: { es: ".", en: ".", zh: "。" } }
                        ],
                        ordo_syntacticus: "Larga oración periódica. Comienza con un ablativo absoluto ('Quibus rebus cognitis') y una cláusula 'cum' histórica. Sigue una serie de cláusulas causales con 'quod' que detallan las pruebas. El verbo principal, 'arbitrabatur', rige una oración de infinitivo ('satis esse causae') y una interrogativa indirecta ('quare...').",
                        notae: "La expresión 'in eum animaduerteret' es un modismo que significa 'tomar medidas contra él' o 'castigarlo'. La acumulación de cláusulas con 'quod' crea un efecto retórico de peso abrumador de la evidencia.",
                        translationes: {
                            es: "Una vez conocidas estas cosas, como a estas sospechas se añadían pruebas muy ciertas —que había hecho pasar a los helvecios a través del territorio de los sécuanos, que se había encargado de que se entregaran rehenes entre ellos, que había hecho todas estas cosas no solo sin su permiso y el del estado, sino incluso sin que ellos mismos lo supieran, que era acusado por el magistrado de los heduos—, (César) consideraba que había motivo suficiente para tomar medidas él mismo contra él o para ordenar al estado que las tomara.",
                            en: "Once these things were known, since to these suspicions were added most certain facts—that he had led the Helvetii through the territory of the Sequani, that he had arranged for hostages to be given between them, that he had done all these things not only without his and the state's permission, but even without them themselves knowing, that he was being accused by the magistrate of the Aedui—he thought there was sufficient reason why he should either take measures against him himself, or order the state to take measures.",
                            zh: "在知曉這些事情之後，由於這些懷疑又加上了非常確鑿的證據——即他曾帶領赫爾維蒂人通過塞夸尼人的領土，他曾安排他們之間交換人質，他做所有這些事不僅未經他本人和邦國的命令，甚至在他們自己不知情的情況下，以及他正被埃杜伊人的政務官指控——（凱撒）認為有足夠的理由，或者由他自己來懲罰他，或者命令邦國來懲罰他。"
                        }
                    },
                    {
                        id_orationis: 'o2',
                        original_lat: "His omnibus rebus unum repugnabat, quod Diuiciaci fratris summum in populum Romanum studium, summam in se uoluntatem, egregiam fidem, iustitiam, temperantiam, cognouerat: nam ne eius supplicio Diuiciaci animum offenderet uerebatur.",
                        verba: [
                            { textus: "His", lemma: "hic", morphologia: "Adjetivo demostrativo, dativo, plural, femenino", syntaxis: "Modificador (de rebus)", translatio: { es: "a estas", en: "to these", zh: "與這些" } },
                            { textus: "omnibus", lemma: "omnis", morphologia: "Adjetivo, dativo, plural, femenino", syntaxis: "Modificador (de rebus)", translatio: { es: "todas", en: "all", zh: "所有" } },
                            { textus: "rebus", lemma: "res", morphologia: "Sustantivo, dativo, plural, femenino", syntaxis: "Objeto Indirecto", translatio: { es: "cosas", en: "matters", zh: "事情" } },
                            { textus: "unum", lemma: "unus", morphologia: "Adjetivo, nominativo, singular, neutro", syntaxis: "Sujeto", translatio: { es: "una sola cosa", en: "one thing", zh: "有一件事" } },
                            { textus: "repugnabat", lemma: "repugno", morphologia: "Verbo, 3ª p, singular, imperfecto, indicativo, activo", syntaxis: "Verbo Principal", translatio: { es: "se oponía", en: "was fighting against", zh: "相抵觸" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "quod", lemma: "quod", morphologia: "Conjunción", syntaxis: "Nexo (explicativo)", translatio: { es: "a saber, que", en: "namely that", zh: "即" } },
                            { textus: "Diuiciaci", lemma: "Diuiciacus", morphologia: "Sustantivo, genitivo, singular, masculino", syntaxis: "C. del Nombre", translatio: { es: "de Diviciaco", en: "of Diviciacus", zh: "迪維西亞庫斯" } },
                            { textus: "fratris", lemma: "frater", morphologia: "Sustantivo, genitivo, singular, masculino", syntaxis: "C. del Nombre", translatio: { es: "su hermano", en: "his brother", zh: "——他兄弟" } },
                            { textus: "summum", lemma: "summus", morphologia: "Adjetivo, acusativo, singular, neutro", syntaxis: "Modificador (de studium)", translatio: { es: "el sumo", en: "the utmost", zh: "極大的" } },
                            { textus: "in", lemma: "in", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "hacia", en: "towards", zh: "對" } },
                            { textus: "populum", lemma: "populus", morphologia: "Sustantivo, acusativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "el pueblo", en: "the people", zh: "人民的" } },
                            { textus: "Romanum", lemma: "Romanus", morphologia: "Adjetivo, acusativo, singular, masculino", syntaxis: "Modificador (de populum)", translatio: { es: "romano", en: "Roman", zh: "羅馬" } },
                            { textus: "studium", lemma: "studium", morphologia: "Sustantivo, acusativo, singular, neutro", syntaxis: "Objeto Directo", translatio: { es: "aprecio", en: "zeal", zh: "熱情" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "summam", lemma: "summus", morphologia: "Adjetivo, acusativo, singular, femenino", syntaxis: "Modificador (de uoluntatem)", translatio: { es: "la suma", en: "the utmost", zh: "極大的" } },
                            { textus: "in", lemma: "in", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "hacia", en: "towards", zh: "對" } },
                            { textus: "se", lemma: "sui", morphologia: "Pronombre, acusativo, singular", syntaxis: "C. preposicional", translatio: { es: "él", en: "himself", zh: "他本人的" } },
                            { textus: "uoluntatem", lemma: "uoluntas", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Objeto Directo", translatio: { es: "buena voluntad", en: "goodwill", zh: "善意" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "egregiam", lemma: "egregius", morphologia: "Adjetivo, acusativo, singular, femenino", syntaxis: "Modificador (de fidem)", translatio: { es: "la egregia", en: "the outstanding", zh: "卓越的" } },
                            { textus: "fidem", lemma: "fides", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Objeto Directo", translatio: { es: "lealtad", en: "faithfulness", zh: "忠誠" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "iustitiam", lemma: "iustitia", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Objeto Directo", translatio: { es: "justicia", en: "justice", zh: "公正" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "temperantiam", lemma: "temperantia", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Objeto Directo", translatio: { es: "moderación", en: "moderation", zh: "節制" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "cognouerat", lemma: "cognosco", morphologia: "Verbo, 3ª p, singular, pluscuamperfecto, indicativo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "conocía", en: "he knew", zh: "他了解" } },
                            { textus: ":", lemma: ":", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ":", en: ":", zh: "：" } },
                            { textus: "nam", lemma: "nam", morphologia: "Conjunción", syntaxis: "Nexo (causal)", translatio: { es: "pues", en: "for", zh: "因為" } },
                            { textus: "ne", lemma: "ne", morphologia: "Conjunción", syntaxis: "Nexo (finalidad negativa)", translatio: { es: "para no", en: "lest", zh: "以免" } },
                            { textus: "eius", lemma: "is", morphologia: "Pronombre, genitivo, singular, masculino", syntaxis: "C. del Nombre (subjetivo)", translatio: { es: "de él", en: "his", zh: "對他的" } },
                            { textus: "supplicio", lemma: "supplicium", morphologia: "Sustantivo, ablativo, singular, neutro", syntaxis: "C.C. de Medio", translatio: { es: "con el castigo", en: "by the punishment", zh: "懲罰" } },
                            { textus: "Diuiciaci", lemma: "Diuiciacus", morphologia: "Sustantivo, genitivo, singular, masculino", syntaxis: "C. del Nombre (posesivo)", translatio: { es: "de Diviciaco", en: "of Diviciacus", zh: "迪維西亞庫斯的" } },
                            { textus: "animum", lemma: "animus", morphologia: "Sustantivo, acusativo, singular, masculino", syntaxis: "Objeto Directo", translatio: { es: "los sentimientos", en: "the feelings", zh: "感情" } },
                            { textus: "offenderet", lemma: "offendo", morphologia: "Verbo, 3ª p, singular, imperfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "ofendiera", en: "he should offend", zh: "傷害" } },
                            { textus: "uerebatur", lemma: "uereor", morphologia: "Verbo, 3ª p, singular, imperfecto, indicativo, deponente", syntaxis: "Verbo Principal", translatio: { es: "temía", en: "he feared", zh: "他擔心" } },
                            { textus: ".", lemma: ".", morphologia: "Puntuación", syntaxis: "Fin de oración", translatio: { es: ".", en: ".", zh: "。" } }
                        ],
                        ordo_syntacticus: "Oración compuesta. La principal ('His... repugnabat') se complementa con una cláusula explicativa introducida por 'quod' ('quod... cognouerat'). La segunda parte ('nam... uerebatur') es una oración causal que explica el temor de César, conteniendo una cláusula de finalidad negativa ('ne... offenderet').",
                        notae: "La larga lista de cualidades de Diviciaco ('studium, uoluntatem, fidem, iustitiam, temperantiam') subraya la alta estima que César le tenía y la gravedad de su dilema.",
                        translationes: {
                            es: "A todas estas consideraciones se oponía una sola cosa: que conocía el sumo aprecio de su hermano Diviciaco por el pueblo romano, su suma buena voluntad hacia él, su egregia lealtad, justicia y moderación; pues temía ofender los sentimientos de Diviciaco con el castigo de aquél.",
                            en: "To all these matters one thing was an obstacle: the fact that he knew of his brother Diviciacus's utmost zeal for the Roman people, his utmost goodwill towards himself, his outstanding faithfulness, justice, and moderation; for he feared that he might offend Diviciacus's feelings by his (Dumnorix's) punishment.",
                            zh: "然而，有一件事與所有這些考慮相抵觸：那就是他了解其兄弟迪維西亞庫斯對羅馬人民極大的熱情、對他本人極大的善意，以及其卓越的忠誠、公正和節制；因為他擔心對杜姆諾里格斯的懲罰會傷害迪維西亞庫斯的感情。"
                        }
                    },
                    {
                        id_orationis: 'o3',
                        original_lat: "Itaque prius quam quicquam conaretur Diuiciacum ad se uocari iubet et cotidianis interpretibus remotis per C. Valerium Troucillum, principem Galliae prouinciae, familiarem suum, cui summam omnium rerum fidem habebat, cum eo conloquitur:",
                        verba: [
                            { textus: "Itaque", lemma: "itaque", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "Así pues", en: "And so", zh: "因此" } },
                            { textus: "prius", lemma: "prius", morphologia: "Adverbio", syntaxis: "Parte de locución", translatio: { es: "antes", en: "before", zh: "在...之前" } },
                            { textus: "quam", lemma: "quam", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "de que", en: "", zh: "" } },
                            { textus: "quicquam", lemma: "quisquam", morphologia: "Pronombre, acusativo, singular, neutro", syntaxis: "Objeto Directo", translatio: { es: "nada", en: "anything", zh: "任何事" } },
                            { textus: "conaretur", lemma: "conor", morphologia: "Verbo, 3ª p, singular, imperfecto, subjuntivo, deponente", syntaxis: "Verbo (de subordinada)", translatio: { es: "intentara", en: "he should attempt", zh: "他嘗試" } },
                            { textus: "Diuiciacum", lemma: "Diuiciacus", morphologia: "Sustantivo, acusativo, singular, masculino", syntaxis: "Sujeto (de infinitiva)", translatio: { es: "a Diviciaco", en: "Diviciacus", zh: "迪維西亞庫斯" } },
                            { textus: "ad", lemma: "ad", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "ante", en: "to", zh: "到" } },
                            { textus: "se", lemma: "sui", morphologia: "Pronombre, acusativo, singular", syntaxis: "C. preposicional", translatio: { es: "sí", en: "him", zh: "他面前" } },
                            { textus: "uocari", lemma: "uoco", morphologia: "Verbo, infinitivo, presente, pasivo", syntaxis: "Verbo (de infinitiva)", translatio: { es: "ser llamado", en: "to be summoned", zh: "被召喚" } },
                            { textus: "iubet", lemma: "iubeo", morphologia: "Verbo, 3ª p, singular, presente, indicativo, activo", syntaxis: "Verbo Principal", translatio: { es: "ordena", en: "he orders", zh: "他命令" } },
                            { textus: "et", lemma: "et", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "y", en: "and", zh: "並且" } },
                            { textus: "cotidianis", lemma: "cotidianus", morphologia: "Adjetivo, ablativo, plural, masculino", syntaxis: "Modificador", translatio: { es: "habituales", en: "usual", zh: "日常的" } },
                            { textus: "interpretibus", lemma: "interpres", morphologia: "Sustantivo, ablativo, plural, masculino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "intérpretes", en: "interpreters", zh: "翻譯" } },
                            { textus: "remotis", lemma: "remoueo", morphologia: "Verbo, participio, perfecto, pasivo, ablativo, plural, masculino", syntaxis: "Verbo (de ablativo absoluto)", translatio: { es: "apartados", en: "having been removed", zh: "被遣開後" } },
                            { textus: "per", lemma: "per", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "por medio de", en: "through", zh: "通過" } },
                            { textus: "C.", lemma: "Gaius", morphologia: "Nombre propio, acusativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "Gayo", en: "Gaius", zh: "蓋烏斯" } },
                            { textus: "Valerium", lemma: "Valerius", morphologia: "Nombre propio, acusativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "Valerio", en: "Valerius", zh: "瓦萊里烏斯" } },
                            { textus: "Troucillum", lemma: "Troucillus", morphologia: "Nombre propio, acusativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "Trocilo", en: "Troucillus", zh: "特勞西盧斯" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "principem", lemma: "princeps", morphologia: "Sustantivo, acusativo, singular, masculino", syntaxis: "Aposición", translatio: { es: "personaje principal", en: "a leading man", zh: "一位領袖" } },
                            { textus: "Galliae", lemma: "Gallia", morphologia: "Sustantivo, genitivo, singular, femenino", syntaxis: "C. del Nombre", translatio: { es: "de la Galia", en: "of the province", zh: "高盧" } },
                            { textus: "prouinciae", lemma: "prouincia", morphologia: "Sustantivo, genitivo, singular, femenino", syntaxis: "Aposición", translatio: { es: "provincia", en: "of Gaul", zh: "行省的" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "familiarem", lemma: "familiaris", morphologia: "Sustantivo, acusativo, singular, masculino", syntaxis: "Aposición", translatio: { es: "amigo íntimo", en: "his intimate friend", zh: "他的密友" } },
                            { textus: "suum", lemma: "suus", morphologia: "Adjetivo posesivo, acusativo, singular, masculino", syntaxis: "Modificador", translatio: { es: "suyo", en: "", zh: "" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "cui", lemma: "qui", morphologia: "Pronombre relativo, dativo, singular, masculino", syntaxis: "Objeto Indirecto", translatio: { es: "en quien", en: "in whom", zh: "他對此人" } },
                            { textus: "summam", lemma: "summus", morphologia: "Adjetivo, acusativo, singular, femenino", syntaxis: "Modificador (de fidem)", translatio: { es: "la máxima", en: "the highest", zh: "最大的" } },
                            { textus: "omnium", lemma: "omnis", morphologia: "Adjetivo, genitivo, plural, femenino", syntaxis: "C. del Nombre", translatio: { es: "de todas", en: "of all", zh: "所有" } },
                            { textus: "rerum", lemma: "res", morphologia: "Sustantivo, genitivo, plural, femenino", syntaxis: "C. del Nombre", translatio: { es: "las cosas", en: "matters", zh: "事情的" } },
                            { textus: "fidem", lemma: "fides", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Objeto Directo", translatio: { es: "confianza", en: "trust", zh: "信任" } },
                            { textus: "habebat", lemma: "habeo", morphologia: "Verbo, 3ª p, singular, imperfecto, indicativo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "tenía", en: "he had", zh: "抱有" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "cum", lemma: "cum", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "con", en: "with", zh: "與" } },
                            { textus: "eo", lemma: "is", morphologia: "Pronombre, ablativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "él", en: "him", zh: "他" } },
                            { textus: "conloquitur", lemma: "conloquor", morphologia: "Verbo, 3ª p, singular, presente, indicativo, deponente", syntaxis: "Verbo Principal", translatio: { es: "conversa", en: "he converses", zh: "交談" } },
                            { textus: ":", lemma: ":", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ":", en: ":", zh: "：" } }
                        ],
                        ordo_syntacticus: "Oración compuesta con una subordinada temporal ('prius quam... conaretur'), dos verbos principales coordinados ('iubet et... conloquitur'), un ablativo absoluto ('cotidianis interpretibus remotis') y una larga aposición con una relativa ('cui... habebat') que describe al intérprete.",
                        notae: "El uso de un intérprete de máxima confianza, C. Valerius Troucillus, subraya la naturaleza delicada y secreta de la conversación.",
                        translationes: {
                            es: "Así pues, antes de intentar nada, ordena que Diviciaco sea llamado ante él y, apartados los intérpretes habituales, conversa con él por medio de C. Valerio Trocilo, personaje principal de la provincia de la Galia, amigo íntimo suyo, en quien tenía la máxima confianza para todas las cosas:",
                            en: "And so, before he attempted anything, he orders Diviciacus to be summoned to him and, with the usual interpreters removed, he converses with him through Gaius Valerius Troucillus, a leading man of the province of Gaul, his intimate friend, in whom he had the highest trust in all matters:",
                            zh: "因此，在他嘗試任何行動之前，他命令將迪維西亞庫斯召到他面前，並且在遣開日常翻譯後，通過蓋烏斯·瓦萊里烏斯·特勞西盧斯與他交談。此人是高盧行省的一位領袖，也是他的密友，凱撒在所有事情上都對他抱有最大的信任："
                        }
                    },
                    {
                        id_orationis: 'o4',
                        original_lat: "simul commonefacit quae ipso praesente in concilio Gallorum de Dumnorige sint dicta, et ostendit quae separatim quisque de eo apud se dixerit;",
                        verba: [
                            { textus: "simul", lemma: "simul", morphologia: "Adverbio", syntaxis: "Modificador", translatio: { es: "al mismo tiempo", en: "at the same time", zh: "同時" } },
                            { textus: "commonefacit", lemma: "commonefacio", morphologia: "Verbo, 3ª p, singular, presente, indicativo, activo", syntaxis: "Verbo Principal", translatio: { es: "le recuerda", en: "he reminds him", zh: "他提醒" } },
                            { textus: "quae", lemma: "qui", morphologia: "Pronombre interrogativo, nominativo, plural, neutro", syntaxis: "Sujeto", translatio: { es: "qué cosas", en: "what things", zh: "哪些話" } },
                            { textus: "ipso", lemma: "ipse", morphologia: "Pronombre, ablativo, singular, masculino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "él mismo", en: "he himself", zh: "他本人" } },
                            { textus: "praesente", lemma: "praesum", morphologia: "Verbo, participio, presente, ablativo, singular, masculino", syntaxis: "Verbo (de ablativo absoluto)", translatio: { es: "estando presente", en: "being present", zh: "在場時" } },
                            { textus: "in", lemma: "in", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "en", en: "in", zh: "在" } },
                            { textus: "concilio", lemma: "concilium", morphologia: "Sustantivo, ablativo, singular, neutro", syntaxis: "C. preposicional", translatio: { es: "la asamblea", en: "the council", zh: "會議上" } },
                            { textus: "Gallorum", lemma: "Galli", morphologia: "Sustantivo, genitivo, plural, masculino", syntaxis: "C. del Nombre", translatio: { es: "de los galos", en: "of the Gauls", zh: "高盧人的" } },
                            { textus: "de", lemma: "de", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "sobre", en: "about", zh: "關於" } },
                            { textus: "Dumnorige", lemma: "Dumnorix", morphologia: "Sustantivo, ablativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "Dúmnorix", en: "Dumnorix", zh: "杜姆諾里格斯" } },
                            { textus: "sint", lemma: "sum", morphologia: "Verbo, 3ª p, plural, presente, subjuntivo", syntaxis: "Verbo (auxiliar)", translatio: { es: "fueron", en: "were", zh: "被" } },
                            { textus: "dicta", lemma: "dico", morphologia: "Verbo, participio, perfecto, pasivo, nominativo, plural, neutro", syntaxis: "Verbo", translatio: { es: "dichas", en: "said", zh: "說過" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "et", lemma: "et", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "y", en: "and", zh: "並" } },
                            { textus: "ostendit", lemma: "ostendo", morphologia: "Verbo, 3ª p, singular, presente, indicativo, activo", syntaxis: "Verbo Principal", translatio: { es: "le muestra", en: "he shows him", zh: "指出了" } },
                            { textus: "quae", lemma: "qui", morphologia: "Pronombre interrogativo, acusativo, plural, neutro", syntaxis: "Objeto Directo", translatio: { es: "qué cosas", en: "what things", zh: "哪些話" } },
                            { textus: "separatim", lemma: "separatim", morphologia: "Adverbio", syntaxis: "Modificador", translatio: { es: "por separado", en: "separately", zh: "分別" } },
                            { textus: "quisque", lemma: "quisque", morphologia: "Pronombre, nominativo, singular, masculino", syntaxis: "Sujeto", translatio: { es: "cada uno", en: "each one", zh: "每個人" } },
                            { textus: "de", lemma: "de", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "sobre", en: "about", zh: "關於" } },
                            { textus: "eo", lemma: "is", morphologia: "Pronombre, ablativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "él", en: "him", zh: "他" } },
                            { textus: "apud", lemma: "apud", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "ante", en: "before", zh: "在他面前" } },
                            { textus: "se", lemma: "sui", morphologia: "Pronombre, acusativo, singular", syntaxis: "C. preposicional", translatio: { es: "él", en: "him", zh: "" } },
                            { textus: "dixerit", lemma: "dico", morphologia: "Verbo, 3ª p, singular, perfecto, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "dijo", en: "had said", zh: "說過" } },
                            { textus: ";", lemma: ";", morphologia: "Puntuación", syntaxis: "Fin de cláusula", translatio: { es: ";", en: ";", zh: "；" } }
                        ],
                        ordo_syntacticus: "Dos oraciones principales coordinadas por 'et'. Cada una ('commonefacit' y 'ostendit') rige una interrogativa indirecta introducida por 'quae', con los verbos en subjuntivo ('sint dicta', 'dixerit').",
                        notae: "'ipso praesente' es un ablativo absoluto que se refiere a Diviciaco: 'estando presente Diviciaco mismo'.",
                        translationes: {
                            es: "al mismo tiempo le recuerda qué cosas fueron dichas sobre Dúmnorix en la asamblea de los galos, estando él mismo presente, y le muestra qué cosas dijo cada uno por separado sobre él en su presencia;",
                            en: "at the same time he reminds him what things were said about Dumnorix in the council of the Gauls with he himself being present, and he shows him what things each one had said separately about him in his presence;",
                            zh: "同時他提醒迪維西亞庫斯，在他本人在場的情況下，高盧人會議上曾說過哪些關於杜姆諾里格斯的話，並指出了每個人在他面前分別說過哪些關於他的話；"
                        }
                    },
                    {
                        id_orationis: 'o5',
                        original_lat: "petit atque hortatur ut sine eius offensione animi uel ipse de eo causa cognita statuat, uel ciuitatem statuere iubeat.",
                        verba: [
                            { textus: "petit", lemma: "peto", morphologia: "Verbo, 3ª p, singular, presente, indicativo, activo", syntaxis: "Verbo Principal", translatio: { es: "le pide", en: "he asks", zh: "他請求" } },
                            { textus: "atque", lemma: "atque", morphologia: "Conjunción", syntaxis: "Nexo", translatio: { es: "y", en: "and", zh: "並且" } },
                            { textus: "hortatur", lemma: "hortor", morphologia: "Verbo, 3ª p, singular, presente, indicativo, deponente", syntaxis: "Verbo Principal", translatio: { es: "le exhorta", en: "he urges", zh: "勸告" } },
                            { textus: "ut", lemma: "ut", morphologia: "Conjunción", syntaxis: "Nexo (completivo)", translatio: { es: "a que", en: "that", zh: "希望" } },
                            { textus: "sine", lemma: "sine", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "sin", en: "without", zh: "不要" } },
                            { textus: "eius", lemma: "is", morphologia: "Pronombre, genitivo, singular, masculino", syntaxis: "C. del Nombre (posesivo)", translatio: { es: "su", en: "his", zh: "他的" } },
                            { textus: "offensione", lemma: "offensio", morphologia: "Sustantivo, ablativo, singular, femenino", syntaxis: "C. preposicional", translatio: { es: "ofensa", en: "offense", zh: "冒犯" } },
                            { textus: "animi", lemma: "animus", morphologia: "Sustantivo, genitivo, singular, masculino", syntaxis: "C. del Nombre", translatio: { es: "de sus sentimientos", en: "of feeling", zh: "感情" } },
                            { textus: "uel", lemma: "uel", morphologia: "Conjunción", syntaxis: "Nexo (disyuntivo)", translatio: { es: "o bien", en: "either", zh: "或者" } },
                            { textus: "ipse", lemma: "ipse", morphologia: "Pronombre, nominativo, singular, masculino", syntaxis: "Sujeto", translatio: { es: "él mismo", en: "he himself", zh: "他自己" } },
                            { textus: "de", lemma: "de", morphologia: "Preposición", syntaxis: "Enlace", translatio: { es: "sobre", en: "concerning", zh: "對" } },
                            { textus: "eo", lemma: "is", morphologia: "Pronombre, ablativo, singular, masculino", syntaxis: "C. preposicional", translatio: { es: "él", en: "him", zh: "他" } },
                            { textus: "causa", lemma: "causa", morphologia: "Sustantivo, ablativo, singular, femenino", syntaxis: "Sujeto (de ablativo absoluto)", translatio: { es: "el caso", en: "the case", zh: "在案件" } },
                            { textus: "cognita", lemma: "cognosco", morphologia: "Verbo, participio, perfecto, pasivo, ablativo, singular, femenino", syntaxis: "Verbo (de ablativo absoluto)", translatio: { es: "una vez examinado", en: "having been examined", zh: "審理後" } },
                            { textus: "statuat", lemma: "statuo", morphologia: "Verbo, 3ª p, singular, presente, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "decida", en: "should decide", zh: "做出裁決" } },
                            { textus: ",", lemma: ",", morphologia: "Puntuación", syntaxis: "Separador", translatio: { es: ",", en: ",", zh: "，" } },
                            { textus: "uel", lemma: "uel", morphologia: "Conjunción", syntaxis: "Nexo (disyuntivo)", translatio: { es: "o bien", en: "or", zh: "或者" } },
                            { textus: "ciuitatem", lemma: "ciuitas", morphologia: "Sustantivo, acusativo, singular, femenino", syntaxis: "Sujeto (de infinitiva)", translatio: { es: "el estado", en: "the state", zh: "讓邦國" } },
                            { textus: "statuere", lemma: "statuo", morphologia: "Verbo, infinitivo, presente, activo", syntaxis: "Verbo (de infinitiva)", translatio: { es: "decidir", en: "to decide", zh: "做出裁決" } },
                            { textus: "iubeat", lemma: "iubeo", morphologia: "Verbo, 3ª p, singular, presente, subjuntivo, activo", syntaxis: "Verbo (de subordinada)", translatio: { es: "ordene", en: "should order", zh: "命令" } },
                            { textus: ".", lemma: ".", morphologia: "Puntuación", syntaxis: "Fin de oración", translatio: { es: ".", en: ".", zh: "。" } }
                        ],
                        ordo_syntacticus: "Los verbos principales ('petit atque hortatur') introducen una cláusula completiva con 'ut'. Dentro de esta, dos opciones se presentan con la correlación 'uel... uel...', ambas con verbos en subjuntivo ('statuat', 'iubeat').",
                        notae: "'sine eius offensione animi' significa literalmente 'sin ofensa de su ánimo', una forma elegante de decir 'sin ofender sus sentimientos'. 'causa cognita' es un ablativo absoluto técnico-legal: 'una vez conocido/examinado el caso'.",
                        translationes: {
                            es: "le pide y le exhorta a que, sin ofender sus sentimientos, o bien decida él mismo sobre el caso una vez examinado, o bien ordene al estado que decida.",
                            en: "he asks and urges that, without any offense to his feelings, he should either decide on the matter himself after examining the case, or order the state to decide.",
                            zh: "他請求並且勸告迪維西亞庫斯，希望在不傷害他感情的情況下，或者由他自己在審理案件後對其作出裁決，或者命令邦國作出裁決。"
                        }
                    }
                ]
            }
        ]
    }
};
